pub mod actions;
pub mod gizmo;
pub mod interactive_element;
pub mod macros;
pub mod plugins;
pub mod renderer;
pub mod store;
pub mod style;
pub mod system;
pub mod ui;
pub mod input;

#[derive(PartialEq)]
pub enum InformationLayer {
    Debug,
}

/*
pub fn get_plugin<'a, Data, Modes, P>(plugins: &'a HashMap<&'static str, Box<(dyn PluginWithOptions<Data> + 'static)>>) -> Option<&'a P>
where
    P: PluginWithOptions<Data> + 'static,
    Data: Default +  'static,
{
    let id = P::identifier();
    if plugins.contains_key(id) {
        // We do the unwrap and rewrapping in Some becase we can be sure that the plugin is of type S since the identifier method
        // is autogenerated and produces unique identifiers for each plugin
        return Some(plugins.get(id).unwrap().as_ref().as_any().downcast_ref::<P>().unwrap());
    }

    None
}

pub fn get_plugin_mut<Data>(_plugins: &mut Vec<Box<dyn PluginWithOptions<Data>>>) -> Option<&mut Modes>
where
    Data:  'static,
{
    todo!()
}
*/