[workspace]

members = [
    "ui",
    "rust_editor",
    "rust_internal",
    "rust_macro",
    "plugin_camera",
    "plugin_grid",
    "plugin_ribbon",
    "plugin_toolbar",
    "plugin_ui_components",
    "plugin_undo_redo"
]