[build]
# The index HTML file to drive the bundling process.
target = "ui/index.html"
# The output dir for all final assets.
dist = "ui/dist"
# The public URL from which assets are to be served.
public_url = "/"
